
module.exports.commands = {
  TS_CREATE: 'TS.CREATE',
  TS_ALTER: 'TS.ALTER',
  TS_ADD: 'TS.ADD',
  TS_INCRBY: 'TS.INCRBY',
  TS_DECRBY: 'TS.DECRBY',
  TS_MADD: 'TS.MADD',
  TS_CREATERULE: 'TS.CREATERULE',
  TS_DELETERULE: 'TS.DELETERULE',
  TS_GET: 'TS.GET',
  TS_MGET: 'TS.MGET',
  TS_RANGE: 'TS.RANGE',
  TS_MRANGE: 'TS.MRANGE',
  TS_INFO: 'TS.INFO',
  TS_QUERYINDEX: 'TS.QUERYINDEX'
};

module.exports.keywords = {
  AGGREGATION: 'AGGREGATION',
  COUNT: 'COUNT',
  FILTER: 'FILTER',
  LABELS: 'LABELS',
  RETENTION: 'RETENTION',
  TIMESTAMP: 'TIMESTAMP',
  UNCOMPRESSED: 'UNCOMPRESSED',
  WITHLABELS: 'WITHLABELS'
};
