
// Keywords
module.exports = {
  AGGREGATION: 'AGGREGATION',
  COUNT: 'COUNT',
  FILTER: 'FILTER',
  LABELS: 'LABELS',
  RETENTION: 'RETENTION',
  TIMESTAMP: 'TIMESTAMP',
  UNCOMPRESSED: 'UNCOMPRESSED',
  WITHLABELS: 'WITHLABELS'
};
